// This file was auto-generated by Fern from our API Definition.

package client

import (
	alerts "go.livesession.io/livesession-go/alerts"
	core "go.livesession.io/livesession-go/core"
	internal "go.livesession.io/livesession-go/internal"
	option "go.livesession.io/livesession-go/option"
	sessions "go.livesession.io/livesession-go/sessions"
	webhooks "go.livesession.io/livesession-go/webhooks"
	websites "go.livesession.io/livesession-go/websites"
	http "net/http"
)

type Client struct {
	baseURL string
	caller  *internal.Caller
	header  http.Header

	Sessions *sessions.Client
	Alerts   *alerts.Client
	Webhooks *webhooks.Client
	Websites *websites.Client
}

func NewClient(opts ...option.RequestOption) *Client {
	options := core.NewRequestOptions(opts...)
	return &Client{
		baseURL: options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
		header:   options.ToHeader(),
		Sessions: sessions.NewClient(opts...),
		Alerts:   alerts.NewClient(opts...),
		Webhooks: webhooks.NewClient(opts...),
		Websites: websites.NewClient(opts...),
	}
}
